/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ContextOption, HttpMethod, MockBody, MockSchema } from "./components/my-component/public-pi";
export { ContextOption, HttpMethod, MockBody, MockSchema } from "./components/my-component/public-pi";
export namespace Components {
    interface MyComponent {
        /**
          * @default 0
         */
        "activeTab": number;
        /**
          * ID del contexto que se usará para cargar un registro específico. - Puede ser establecido por el host como una propiedad (`contextId`). - Se utiliza en la pestaña "Cargar"; al pulsar "Cargar registro" el componente   emite `loadContextEvent` con este identificador para que el host lo procese.
          * @default 1
         */
        "contextId": number;
        /**
          * List of available context options. Can be provided by the host; defaults to the three built-in options. Marked mutable so the component can update it from the UI (demo mode).
          * @default [     { id: 1, value: '---------', useMock: false },     { id: 2, value: 'Usar HTTP', useMock: false },     { id: 3, value: 'Usar Data', useMock: true },   ]
         */
        "contextOptions": ContextOption[];
        /**
          * @default 0
         */
        "delayMs": number;
        /**
          * Optional initial headers provided by the host (made mutable so component may edit them)
          * @default {}
         */
        "headers": Record<string, string>;
        /**
          * Codes that populate the Código HTTP select. Can be set by the host as a prop.
          * @default [200, 204, 400, 500]
         */
        "httpCodeResponse": number[];
        /**
          * @default 200
         */
        "httpCodeResponseValue": number;
        /**
          * @default 'GET'
         */
        "httpMethod": HttpMethod;
        /**
          * List of available HTTP methods. Can be provided by the host; defaults to the five built-in options.
          * @default [     'GET',     'POST',     'PUT',     'DELETE',     'PATCH'   ]
         */
        "httpMethods": HttpMethod[];
        /**
          * @default ''
         */
        "nameMock": string;
        /**
          * @default '{}'
         */
        "responseBody": string;
        /**
          * The current context type can be provided by the host as a ContextOption prop
         */
        "selectedContext"?: ContextOption;
        /**
          * @default ''
         */
        "serviceCode": string;
        /**
          * @default ''
         */
        "url": string;
    }
}
export interface MyComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyComponentElement;
}
declare global {
    interface HTMLMyComponentElementEventMap {
        "saveMockSchemaEvent": MockSchema;
        "saveMockBodyEvent": MockBody;
        "saveHeadersEvent": Record<string, string>;
        "loadContextEvent": number;
        "contextTypeChangeEvent": ContextOption;
        "reloadEvent": void;
    }
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyComponentElementEventMap>(type: K, listener: (this: HTMLMyComponentElement, ev: MyComponentCustomEvent<HTMLMyComponentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyComponentElementEventMap>(type: K, listener: (this: HTMLMyComponentElement, ev: MyComponentCustomEvent<HTMLMyComponentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * @default 0
         */
        "activeTab"?: number;
        /**
          * ID del contexto que se usará para cargar un registro específico. - Puede ser establecido por el host como una propiedad (`contextId`). - Se utiliza en la pestaña "Cargar"; al pulsar "Cargar registro" el componente   emite `loadContextEvent` con este identificador para que el host lo procese.
          * @default 1
         */
        "contextId"?: number;
        /**
          * List of available context options. Can be provided by the host; defaults to the three built-in options. Marked mutable so the component can update it from the UI (demo mode).
          * @default [     { id: 1, value: '---------', useMock: false },     { id: 2, value: 'Usar HTTP', useMock: false },     { id: 3, value: 'Usar Data', useMock: true },   ]
         */
        "contextOptions"?: ContextOption[];
        /**
          * @default 0
         */
        "delayMs"?: number;
        /**
          * Optional initial headers provided by the host (made mutable so component may edit them)
          * @default {}
         */
        "headers"?: Record<string, string>;
        /**
          * Codes that populate the Código HTTP select. Can be set by the host as a prop.
          * @default [200, 204, 400, 500]
         */
        "httpCodeResponse"?: number[];
        /**
          * @default 200
         */
        "httpCodeResponseValue"?: number;
        /**
          * @default 'GET'
         */
        "httpMethod"?: HttpMethod;
        /**
          * List of available HTTP methods. Can be provided by the host; defaults to the five built-in options.
          * @default [     'GET',     'POST',     'PUT',     'DELETE',     'PATCH'   ]
         */
        "httpMethods"?: HttpMethod[];
        /**
          * @default ''
         */
        "nameMock"?: string;
        "onContextTypeChangeEvent"?: (event: MyComponentCustomEvent<ContextOption>) => void;
        "onLoadContextEvent"?: (event: MyComponentCustomEvent<number>) => void;
        "onReloadEvent"?: (event: MyComponentCustomEvent<void>) => void;
        "onSaveHeadersEvent"?: (event: MyComponentCustomEvent<Record<string, string>>) => void;
        "onSaveMockBodyEvent"?: (event: MyComponentCustomEvent<MockBody>) => void;
        /**
          * Events emitted so parent implementations can listen
         */
        "onSaveMockSchemaEvent"?: (event: MyComponentCustomEvent<MockSchema>) => void;
        /**
          * @default '{}'
         */
        "responseBody"?: string;
        /**
          * The current context type can be provided by the host as a ContextOption prop
         */
        "selectedContext"?: ContextOption;
        /**
          * @default ''
         */
        "serviceCode"?: string;
        /**
          * @default ''
         */
        "url"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
